ENV='3s5z_vs_3s6z'
MAX_STEPS=3000000

OMP_NUM_THREADS=10 CUDA_VISIBLE_DEVICES=1 python main.py \
 --algorithm 'ACORM' \
 --env_name ${ENV}\
 --device 'cuda:0'\
 --max_train_steps ${MAX_STEPS}\
 --seed 0 \
 --epsilon 1.0                 \
 --epsilon_decay_steps 80000 \
 --epsilon_min 0.02     \
 --use_hard_update False \
 --use_lr_decay True     \
 --lr_decay_steps 500    \
 --lr_decay_rate 0.98    \
 --train_recl_freq 100 \
 --use_ln False \
 --role_tau 0.005  \
 --cluster_num 3   \
 --agent_embedding_dim 128 \
 --hyper_layers_num 2      \
 --lr +6e-4  \
 --recl_lr +8e-4   \
 --role_embedding_dim 64   \
 --save_path './result/acorm'\
 --att_dim 128  \
 --att_out_dim 64  \
 --n_heads 4   \
 --soft_temperature 1.0  \
 --state_embed_dim 64   \
 --max_history 10 \
 --num_process_per_gpu 1 \
&
OMP_NUM_THREADS=10 CUDA_VISIBLE_DEVICES=1 python main.py \
 --algorithm 'ACORM' \
 --env_name ${ENV}\
 --device 'cuda:0'\
 --max_train_steps ${MAX_STEPS} \
 --seed 1 \
 --epsilon 1.0                 \
 --epsilon_decay_steps 80000 \
 --epsilon_min 0.02     \
 --use_hard_update False \
 --use_lr_decay True     \
 --lr_decay_steps 500    \
 --lr_decay_rate 0.98    \
 --train_recl_freq 100 \
 --use_ln False \
 --role_tau 0.005  \
 --cluster_num 3   \
 --agent_embedding_dim 128 \
 --hyper_layers_num 2      \
 --lr +6e-4  \
 --recl_lr +8e-4   \
 --role_embedding_dim 64   \
 --save_path './result/acorm'\
 --att_dim 128  \
 --att_out_dim 64  \
 --n_heads 4   \
 --soft_temperature 1.0  \
 --state_embed_dim 64   \
 --max_history 10 \
 --num_process_per_gpu 1 \
&
OMP_NUM_THREADS=10 CUDA_VISIBLE_DEVICES=2 python main.py \
 --algorithm 'ACORM' \
 --env_name ${ENV}\
 --device 'cuda:0'\
 --max_train_steps ${MAX_STEPS} \
 --seed 2 \
 --epsilon 1.0                 \
 --epsilon_decay_steps 80000 \
 --epsilon_min 0.02     \
 --use_hard_update False \
 --use_lr_decay True     \
 --lr_decay_steps 500    \
 --lr_decay_rate 0.98    \
 --train_recl_freq 100 \
 --use_ln False \
 --role_tau 0.005  \
 --cluster_num 3   \
 --agent_embedding_dim 128 \
 --hyper_layers_num 2      \
 --lr +6e-4  \
 --recl_lr +8e-4   \
 --role_embedding_dim 64   \
 --save_path './result/acorm'\
 --att_dim 128  \
 --att_out_dim 64  \
 --n_heads 4   \
 --soft_temperature 1.0  \
 --state_embed_dim 64   \
 --max_history 10 \
 --num_process_per_gpu 1 \
&
OMP_NUM_THREADS=10 CUDA_VISIBLE_DEVICES=3 python main.py \
 --algorithm 'ACORM' \
 --env_name ${ENV}\
 --device 'cuda:0'\
 --max_train_steps ${MAX_STEPS} \
 --seed 3 \
 --epsilon 1.0                 \
 --epsilon_decay_steps 80000 \
 --epsilon_min 0.02     \
 --use_hard_update False \
 --use_lr_decay True     \
 --lr_decay_steps 500    \
 --lr_decay_rate 0.98    \
 --train_recl_freq 100 \
 --use_ln False \
 --role_tau 0.005  \
 --cluster_num 3   \
 --agent_embedding_dim 128 \
 --hyper_layers_num 2      \
 --lr +6e-4  \
 --recl_lr +8e-4   \
 --role_embedding_dim 64   \
 --save_path './result/acorm'\
 --att_dim 128  \
 --att_out_dim 64  \
 --n_heads 4   \
 --soft_temperature 1.0  \
 --state_embed_dim 64   \
 --max_history 10 \
 --num_process_per_gpu 1 \
&
OMP_NUM_THREADS=10 CUDA_VISIBLE_DEVICES=4 python main.py \
 --algorithm 'ACORM' \
 --env_name ${ENV}\
 --device 'cuda:0'\
 --max_train_steps ${MAX_STEPS} \
 --seed 4 \
 --epsilon 1.0                 \
 --epsilon_decay_steps 80000 \
 --epsilon_min 0.02     \
 --use_hard_update False \
 --use_lr_decay True     \
 --lr_decay_steps 500    \
 --lr_decay_rate 0.98    \
 --train_recl_freq 100 \
 --use_ln False \
 --role_tau 0.005  \
 --cluster_num 3   \
 --agent_embedding_dim 128 \
 --hyper_layers_num 2      \
 --lr +6e-4  \
 --recl_lr +8e-4   \
 --role_embedding_dim 64   \
 --save_path './result/acorm'\
 --att_dim 128  \
 --att_out_dim 64  \
 --n_heads 4   \
 --soft_temperature 1.0  \
 --state_embed_dim 64   \
 --max_history 10 \
 --num_process_per_gpu 1 \
&
OMP_NUM_THREADS=10 CUDA_VISIBLE_DEVICES=5 python main.py \
 --algorithm 'ACORM' \
 --env_name ${ENV}\
 --device 'cuda:0'\
 --max_train_steps ${MAX_STEPS} \
 --seed 5 \
 --epsilon 1.0                 \
 --epsilon_decay_steps 80000 \
 --epsilon_min 0.02     \
 --use_hard_update False \
 --use_lr_decay True     \
 --lr_decay_steps 500    \
 --lr_decay_rate 0.98    \
 --train_recl_freq 100 \
 --use_ln False \
 --role_tau 0.005  \
 --cluster_num 3   \
 --agent_embedding_dim 128 \
 --hyper_layers_num 2      \
 --lr +6e-4  \
 --recl_lr +8e-4   \
 --role_embedding_dim 64   \
 --save_path './result/acorm'\
 --att_dim 128  \
 --att_out_dim 64  \
 --n_heads 4   \
 --soft_temperature 1.0  \
 --state_embed_dim 64   \
 --max_history 10 \
 --num_process_per_gpu 1 \

